version: 0.2

env:
  variables:
    hugo_version: "0.69.2"

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
      - dpkg -i "hugo_${hugo_version}_Linux-64bit.deb"
    finally:
      - hugo version
  build:
    commands:
      - hugo
  post_build:
    commands:
      - echo "Build finished"
